# Generated by Django 4.0 on 2024-04-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField()),
                ('case_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('sex_gender', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('educational_attainment', models.CharField(max_length=50)),
                ('means_of_income', models.CharField(max_length=50)),
                ('estimated_income', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
