# Generated by Django 4.0 on 2024-04-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_personalinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='range',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
