# Generated by Django 4.0 on 2024-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_personalinfo_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='problem',
            field=models.CharField(max_length=250),
        ),
    ]
