# Generated by Django 4.0 on 2024-04-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_educattain_estincome_genders_maritalstatus_ranges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranges',
            name='range1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranges',
            name='range2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
