# Generated by Django 4.0 on 2024-04-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_ranges_range1_ranges_range2'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='incomes',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
    ]
