# Generated by Django 4.0 on 2024-04-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_personalinfo_incomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='incomes',
        ),
    ]
