# Generated by Django 4.0 on 2024-04-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_remove_personalinfo_incomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='money',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
    ]
