# Generated by Django 4.0 on 2024-04-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='Requests',
        ),
    ]
