# Generated by Django 4.0 on 2024-04-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0012_rename_request_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='document',
            field=models.FileField(default=1, upload_to='static/documents/'),
            preserve_default=False,
        ),
    ]
